server:
  port: 8080
spring:
  redis:
    host: 47.113.102.247
    port: 6381
  rabbitmq:
    host: 47.113.102.247
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirms: true
    publisher-confirm-type: CORRELATED
  datasource:
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.113.102.247:3306/sw_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 112200
      # 连接池设置
      initial-size: 10
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 90000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # Oracle请使用select 1 from dual
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

    second:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.113.102.247:3306/sw_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 112200
      initial-size: 10
      min-idle: 5
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 90000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
#      cluster-nodes: 106.54.200.122:9300,106.54.200.122:9301,106.54.200.122:9302
#      cluster-name: mall-es




jackson:
  time-zone: GMT+8
  date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: sw.java.elk
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    sw.java.elk.dao:



